// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKdX099DUD1PWzZlzLC4Ue1kP2iCefd_M',
    appId: '1:119511501583:web:a835b1e6f452c5e6638c7a',
    messagingSenderId: '119511501583',
    projectId: 'events-calendary',
    authDomain: 'events-calendary.firebaseapp.com',
    storageBucket: 'events-calendary.firebasestorage.app',
    measurementId: 'G-SG3BFG23D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqSyW6d49121rlhkxcbsqtehXen6-Ip-A',
    appId: '1:119511501583:android:4c5387f7cf36ba76638c7a',
    messagingSenderId: '119511501583',
    projectId: 'events-calendary',
    storageBucket: 'events-calendary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDVmFdVGsYvuzX-67KbLTFgbSsRDlkvYA',
    appId: '1:119511501583:ios:41c6f21bebee5940638c7a',
    messagingSenderId: '119511501583',
    projectId: 'events-calendary',
    storageBucket: 'events-calendary.firebasestorage.app',
    iosBundleId: 'com.example.calendaryNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDVmFdVGsYvuzX-67KbLTFgbSsRDlkvYA',
    appId: '1:119511501583:ios:41c6f21bebee5940638c7a',
    messagingSenderId: '119511501583',
    projectId: 'events-calendary',
    storageBucket: 'events-calendary.firebasestorage.app',
    iosBundleId: 'com.example.calendaryNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKdX099DUD1PWzZlzLC4Ue1kP2iCefd_M',
    appId: '1:119511501583:web:aeb2d1a3f5184a51638c7a',
    messagingSenderId: '119511501583',
    projectId: 'events-calendary',
    authDomain: 'events-calendary.firebaseapp.com',
    storageBucket: 'events-calendary.firebasestorage.app',
    measurementId: 'G-8KTSJDF73V',
  );
}
